[versions]
java = "21"
springBoot = "3.2.4" # 이것만 바꾸면 됨
dependencyManagement = "1.1.4"
jjwt = "0.11.5"      # 스프링이 모르는 외부 라이브러리만 버전 명시

[libraries]
# --- Spring Boot Managed ---
spring-boot-starter-web = {group = "org.springframework.boot", name = "spring-boot-starter-web"}
spring-boot-starter-data-jpa = {group = "org.springframework.boot", name = "spring-boot-starter-data-jpa"}
spring-boot-starter-batch = { group = "org.springframework.boot", name = "spring-boot-starter-batch" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }

lombok = {group = "org.projectlombok", name = "lombok"}
h2 = {group = "com.h2database", name = "h2"}

spring-boot-configuration-processor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor" }

# --- External Libraries ---
jjwt-api = { group = "io.jsonwebtoken", name = "jjwt-api", version.ref = "jjwt" }
jjwt-impl = { group = "io.jsonwebtoken", name = "jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { group = "io.jsonwebtoken", name = "jjwt-jackson", version.ref = "jjwt" }

[bundles]
# 번들 기능: 이 3개를 묶어서 'libs.bundles.jjwt'로 한방에 부를 수 있음
jjwt = ["jjwt-api", "jjwt-impl", "jjwt-jackson"]

[plugins]
springBoot = {id = "org.springframework.boot", version.ref = "springBoot"}
dependencyManagement = { id = "io.spring.dependency-management", version.ref = "dependencyManagement" }